SELECT srv43968_test.containers.ID, SUM(CAPACITY) AS LOADED_CAPACITY
FROM 
	(SELECT ID, 
		WIDTH*LENGTH*HEIGHT AS CAPACITY,
		(CASE
			WHEN ID_CONTAINER_MOVE = 0 THEN ID_CONTAINER
			ELSE ID_CONTAINER_MOVE
		END) AS ID_CONTAINER
	FROM srv43968_test.boxes
	WHERE ID_STOCK = 1
		AND STATUS = 0
		AND NN_REZERV = 0) AS boxes_new
RIGHT JOIN srv43968_test.containers
	ON srv43968_test.containers.ID = boxes_new.ID_CONTAINER
WHERE STATUS = 0
GROUP BY srv43968_test.containers.ID
HAVING LOADED_CAPACITY > 500000;
		
		
